from manimlib.imports import *

class SumRule(Scene):
    def construct(self):
        introimg = ImageMobject('/home/niwhskal/Downloads/Untitled45.png').to_corner(DR).scale(0.2).shift(DOWN+RIGHT)
        self.add(introimg)
        image = ImageMobject("/home/niwhskal/Pictures/table_final.png").scale(1.5) 
        intext = TextMobject("Table containing probabilities").next_to(image, TOP)
        self.add(intext)
        self.play(FadeIn(image)) 
        self.wait(4)
        image.generate_target()
        image.target.to_edge(LEFT)
        self.remove(intext)
        self.play(MoveToTarget(image))
        
        introtext = TextMobject(r"P(Y = Indian) =").to_corner(UL).scale(0.6)
        que = TextMobject(r"?").next_to(introtext).scale(0.7)
        rect_small = Rectangle(height=0.54, width=1.62, color = RED).next_to(image).shift(1.95*LEFT + 0.62*UP)
        self.play(ShowCreation(rect_small))
        self.play(Write(introtext))  
        self.add(que)
        self.wait(1)
        self.remove(rect_small)
        rect = Rectangle(height=0.52, width=7.8, color = RED).next_to(image).shift(8.1*LEFT + 0.62*UP)
        self.play(ShowCreation(rect)) 
        self.wait(1)
        self.remove(que)
        arrow = CurvedArrow(rect.get_edge_center(UP), introtext.get_edge_center(RIGHT)+RIGHT,angle= -TAU/4,color = BLUE)
        self.play(ShowCreation(arrow))

#        sumtext_or = TextMobject(r"P(0 dates, Indian) OR P(1 date, Indian) OR P(2 dates, Indian)").scale(0.6).next_to(introtext) 
        sumtext = TextMobject(r"P(0 dates, Indian) + P(1 date, Indian) + P(2 dates, Indian) + P(3 dates, Indian)").scale(0.6).next_to(introtext) 
        self.wait(0.5)
        self.remove(arrow)
        self.play(Write(sumtext, run_time =3))
        self.wait(1)
        finaltext = TextMobject("$= \\sum_{x \in {0,1,2,3}} P(X=x, Y=Indian)$").next_to(sumtext, DOWN).scale(0.6)
        self.play(Write(finaltext))
        self.wait(2)
        self.play(ShowCreation(SurroundingRectangle(finaltext, fill_opacity=0)))
        self.wait(10)
